Adding multibyte support
jasny/twig-extensions pull request #13
Opened 2017-05-11 09:35 UTC by alianora

I've added multibyte string support in TextExtension. Support is conditional so library doesn't requires php mb_extension.

2017-05-31 21:04 UTC, jasny requested changes
@mariuszkaczanowski Great, but this makes the code unreadable because of all the `if` statements.

Instead add methods like this

```php
protected function stripos($string, $substr)
{
    return $this->useMultiByte() ? mb_stripos($string, $substr) : stripos($string, $substr);
}
```

2017-06-07 07:30 UTC, mariuszkaczanowski commented
Original version:
```php
return strlen($value) <= $length ? $value : substr($value, 0, $length - strlen($replace)) . $replace;
```
My first version:
```php
if (function_exists('mb_strlen') && function_exists('mb_substr')) {
     return mb_strlen($value) <= $length ? $value : mb_substr($value, 0, $length - strlen($replace)) . $replace;
}
return strlen($value) <= $length ? $value : substr($value, 0, $length - strlen($replace)) . $replace;
```
After Yours suggestions:
```php
$strLenValue = $this->useMultiByte() ? mb_strlen($value) : strlen($value);
$strLenReplace = $this->useMultiByte() ? mb_strlen($replace) : strlen($replace);
$subStr = $this->useMultiByte() ? mb_substr($value, 0, $length - $strLenReplace) : substr($value, 0, $length - $strLenReplace);
return $strLenValue <= $length ? $value : $subStr . $replace;
```
Now I don't know what is the best. Besides $subStr will be calculated everytime not conditionaly. Any suggestions?

2017-06-07 07:35 UTC, mariuszkaczanowski commented
Maybe the best will be add separate class MBTextExtension and let users choose what they want to use?

2017-06-13 09:56 UTC, jasny commented
@mariuszkaczanowski Please don't put the inline if statements in the code. That's almost as unreadable. Pleas add protected functions which wraps each str/mb_str function.

```php
protected function stripos($string, $substr)
protected function strlen($string, $substr)
protected function substr($string, $substr)
```

Instead of using a `useMultibyte()` method, you can also use a protected property `$useMultibyte`, which is set in the constructor.

2020-03-06 10:00 UTC, closed without merging